version: '3.5'

services:
  

  db:
    image: postgres:14.3-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: keeper_dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
